/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.util.ArrayList;
/**
 *
 * @author angel
 */
public class Mostrar_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_Clientes
     */
    public Mostrar_Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnMostrarTodo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablita = new javax.swing.JTable();
        Fondo_aplicacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton1.setText("Menu principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 160, 60));

        jButton2.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jButton2.setText("Salir ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 130, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/4105938-account-card-id-identification-identity.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 210, 170));

        btnMostrarTodo.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        btnMostrarTodo.setText("Mostrar!");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 150, 80));

        tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Correo", "Edad", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablita);
        if (tablita.getColumnModel().getColumnCount() > 0) {
            tablita.getColumnModel().getColumn(0).setResizable(false);
            tablita.getColumnModel().getColumn(1).setResizable(false);
            tablita.getColumnModel().getColumn(2).setResizable(false);
            tablita.getColumnModel().getColumn(3).setResizable(false);
            tablita.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 570, 540));

        Fondo_aplicacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpaper-4655085.png"))); // NOI18N
        getContentPane().add(Fondo_aplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
Interfaz principal = new Interfaz();
principal.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        // TODO add your handling code here:
        String arreglo [][] = new String [controlClientes.clientes.size()][5];
        for (int i = 0; i < controlClientes.clientes.size(); i++) {
            arreglo[i][0] =  controlClientes.clientes.get(i).getId();
            arreglo[i][1] =  controlClientes.clientes.get(i).getNombre();
            arreglo[i][2] =  controlClientes.clientes.get(i).getCorreo();
            arreglo[i][3] = String.valueOf( controlClientes.clientes.get(i).getEdad());
            arreglo[i][4] = String.valueOf( controlClientes.clientes.get(i).getTelefono()); 
        }
        tablita.setModel(new javax.swing.table.DefaultTableModel(
            arreglo,
            new String [] {
                "Id", "Nombre", "Correo", "Edad", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablita);
        if (tablita.getColumnModel().getColumnCount() > 0) {
            tablita.getColumnModel().getColumn(0).setResizable(false);
            tablita.getColumnModel().getColumn(1).setResizable(false);
            tablita.getColumnModel().getColumn(2).setResizable(false);
            tablita.getColumnModel().getColumn(3).setResizable(false);
            tablita.getColumnModel().getColumn(4).setResizable(false);
        }
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo_aplicacion;
    private javax.swing.JToggleButton btnMostrarTodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablita;
    // End of variables declaration//GEN-END:variables
}
